version: '3.6'

services:
    web:
        image: httpd:2.4.46
        restart: unless-stopped
        networks:
            - frontend
            - backend
        ports:
            - "80:80"
            - "127.0.0.1:8080:8080"
        depends_on:
            - db
            - php-fpm
            - adminer
        volumes:
            - type: bind
              source: ./www
              target: /var/www
              volume: 
                nocopy: true
            - "./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro"
            - "./httpd/modules.conf:/usr/local/apache2/conf/modules.conf:ro"
        logging:
            driver: "json-file"
            options:
                max-size: "100k"
                max-file: "10"

    php-fpm:
        build: "./php-fpm/"
        networks:
            - backend
        volumes:
            - type: bind
              source: ./www
              target: /var/www
            - type: bind
              source: ./php-fpm/www.conf
              target: /usr/local/etc/php-fpm.d/www.conf
        env_file: 
            - ".env"
        logging:
            driver: "json-file"
            options:
                max-size: "10k"
                max-file: "3"
    db:
        build:
            context: "./mariadb"
        restart: unless-stopped
        cap_add:
            - SYS_NICE
        volumes:
            - type: volume 
              source: db-data
              target: /var/lib/mysql
              volume:
                  nocopy: true
        networks:
            - backend
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
        env_file:
            - ".env"
        logging:
            driver: "json-file"
            options:
                max-size: "10k"
                max-file: "3"

    adminer:
        image: adminer:4.8.0-fastcgi
        restart: unless-stopped
        networks:
            - backend
        depends_on:
            - db
        logging:
            driver: "json-file"
            options:
                max-size: "10k"
                max-file: "3"

volumes:
    db-data:

networks:
    backend:
    frontend:
