
global:
    scrape_interval: 30s
    scrape_timeout: 10s

rule_files:
    - alerts.yml

scrape_configs:
    - job_name: prometheus
      metrics_path: /metrics
      scrape_interval: "15s"
      static_configs:
        - targets:
            - 'prometheus:9090'
    - job_name: httpd
      metrics_path: /metrics
      scrape_interval: "15s"
      static_configs:
        - targets:
            - 'httpd_export:9117'
